# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/PbFloor/PbFloorReqIdl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import CommonReq_pb2 as proto_dot_CommonReq__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!proto/PbFloor/PbFloorReqIdl.proto\x12\x0cTiebaDesktop\x1a\x15proto/CommonReq.proto\"\x83\x03\n\x0f\x44\x61taReq_PbFloor\x12\n\n\x02kz\x18\x01 \x01(\x03\x12\x0b\n\x03pid\x18\x02 \x01(\x03\x12\x0c\n\x04spid\x18\x03 \x01(\x03\x12\n\n\x02pn\x18\x04 \x01(\x05\x12\r\n\x05scr_w\x18\x05 \x01(\x05\x12\r\n\x05scr_h\x18\x06 \x01(\x05\x12\x0f\n\x07scr_dip\x18\x07 \x01(\x01\x12\x0f\n\x07st_type\x18\x08 \x01(\t\x12\'\n\x06\x63ommon\x18\t \x01(\x0b\x32\x17.TiebaDesktop.CommonReq\x12\x17\n\x0fis_comm_reverse\x18\n \x01(\x05\x12\x10\n\x08\x66orum_id\x18\x0b \x01(\x03\x12\x13\n\x0bori_ugc_nid\x18\x0c \x01(\t\x12\x13\n\x0bori_ugc_tid\x18\r \x01(\t\x12\x14\n\x0cori_ugc_type\x18\x0f \x01(\x05\x12\x13\n\x0bori_ugc_vid\x18\x10 \x01(\t\x12\x13\n\x0btop_ugc_pid\x18\x11 \x01(\t\x12\x15\n\rrequest_times\x18\x12 \x01(\x05\x12\x0c\n\x04sort\x18\x13 \x01(\x05\x12\x1a\n\x12out_floor_post_ids\x18\x14 \x01(\t\"<\n\rPbFloorReqIdl\x12+\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x1d.TiebaDesktop.DataReq_PbFloorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.PbFloor.PbFloorReqIdl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATAREQ_PBFLOOR._serialized_start=75
  _DATAREQ_PBFLOOR._serialized_end=462
  _PBFLOORREQIDL._serialized_start=464
  _PBFLOORREQIDL._serialized_end=524
# @@protoc_insertion_point(module_scope)
