# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/PbFloor/PbFloorResIdl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import Error_pb2 as proto_dot_Error__pb2
from proto import Anti_pb2 as proto_dot_Anti__pb2
from proto import CommentPublisherConfig_pb2 as proto_dot_CommentPublisherConfig__pb2
from proto import FeedKV_pb2 as proto_dot_FeedKV__pb2
from proto import Page_pb2 as proto_dot_Page__pb2
from proto import Post_pb2 as proto_dot_Post__pb2
from proto import SimpleForum_pb2 as proto_dot_SimpleForum__pb2
from proto import SubPostList_pb2 as proto_dot_SubPostList__pb2
from proto import TabInfo_pb2 as proto_dot_TabInfo__pb2
from proto import ThreadInfo_pb2 as proto_dot_ThreadInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!proto/PbFloor/PbFloorResIdl.proto\x12\x0cTiebaDesktop\x1a\x11proto/Error.proto\x1a\x10proto/Anti.proto\x1a\"proto/CommentPublisherConfig.proto\x1a\x12proto/FeedKV.proto\x1a\x10proto/Page.proto\x1a\x10proto/Post.proto\x1a\x17proto/SimpleForum.proto\x1a\x17proto/SubPostList.proto\x1a\x13proto/TabInfo.proto\x1a\x16proto/ThreadInfo.proto\"\x9f\x04\n\x0f\x44\x61taRes_PbFloor\x12 \n\x04page\x18\x01 \x01(\x0b\x32\x12.TiebaDesktop.Page\x12 \n\x04\x61nti\x18\x02 \x01(\x0b\x32\x12.TiebaDesktop.Anti\x12 \n\x04post\x18\x03 \x01(\x0b\x32\x12.TiebaDesktop.Post\x12/\n\x0csubpost_list\x18\x04 \x03(\x0b\x32\x19.TiebaDesktop.SubPostList\x12(\n\x06thread\x18\x05 \x01(\x0b\x32\x18.TiebaDesktop.ThreadInfo\x12(\n\x05\x66orum\x18\x06 \x01(\x0b\x32\x19.TiebaDesktop.SimpleForum\x12\x13\n\x0bserver_time\x18\x07 \x01(\x05\x12\x30\n\rdisplay_forum\x18\x08 \x01(\x0b\x32\x19.TiebaDesktop.SimpleForum\x12\x16\n\x0eis_black_white\x18\t \x01(\x05\x12\'\n\tlog_param\x18\n \x03(\x0b\x32\x14.TiebaDesktop.FeedKV\x12\x46\n\x18\x63omment_publisher_config\x18\x0c \x01(\x0b\x32$.TiebaDesktop.CommentPublisherConfig\x12\x13\n\x0bsubpost_num\x18\r \x01(\x05\x12\'\n\x08tab_info\x18\x0e \x03(\x0b\x32\x15.TiebaDesktop.TabInfo\x12\x13\n\x0b\x63urrent_tab\x18\x0f \x01(\r\"`\n\rPbFloorResIdl\x12\"\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x13.TiebaDesktop.Error\x12+\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1d.TiebaDesktop.DataRes_PbFloorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.PbFloor.PbFloorResIdl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATARES_PBFLOOR._serialized_start=276
  _DATARES_PBFLOOR._serialized_end=819
  _PBFLOORRESIDL._serialized_start=821
  _PBFLOORRESIDL._serialized_end=917
# @@protoc_insertion_point(module_scope)
