# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/PbPage/PbPageResIdl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import Error_pb2 as proto_dot_Error__pb2
from proto import Page_pb2 as proto_dot_Page__pb2
from proto.PbPage import PbSortType_pb2 as proto_dot_PbPage_dot_PbSortType__pb2
from proto import Post_pb2 as proto_dot_Post__pb2
from proto import SimpleForum_pb2 as proto_dot_SimpleForum__pb2
from proto import ThreadInfo_pb2 as proto_dot_ThreadInfo__pb2
from proto import User_pb2 as proto_dot_User__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto/PbPage/PbPageResIdl.proto\x12\x0cTiebaDesktop\x1a\x11proto/Error.proto\x1a\x10proto/Page.proto\x1a\x1dproto/PbPage/PbSortType.proto\x1a\x10proto/Post.proto\x1a\x17proto/SimpleForum.proto\x1a\x16proto/ThreadInfo.proto\x1a\x10proto/User.proto\"\xed\x03\n\x0e\x44\x61taRes_PbPage\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.TiebaDesktop.User\x12(\n\x05\x66orum\x18\x02 \x01(\x0b\x32\x19.TiebaDesktop.SimpleForum\x12 \n\x04page\x18\x03 \x01(\x0b\x32\x12.TiebaDesktop.Page\x12%\n\tpost_list\x18\x06 \x03(\x0b\x32\x12.TiebaDesktop.Post\x12\x11\n\thas_floor\x18\x07 \x01(\x05\x12(\n\x06thread\x18\x08 \x01(\x0b\x32\x18.TiebaDesktop.ThreadInfo\x12,\n\x10\x66irst_floor_post\x18& \x01(\x0b\x32\x12.TiebaDesktop.Post\x12\x30\n\rdisplay_forum\x18\' \x01(\x0b\x32\x19.TiebaDesktop.SimpleForum\x12.\n\x0cpb_sort_info\x18\x31 \x03(\x0b\x32\x18.TiebaDesktop.PbSortType\x12\x11\n\tsort_type\x18\x32 \x01(\x05\x12&\n\ntop_answer\x18I \x01(\x0b\x32\x12.TiebaDesktop.Post\x12\x17\n\x0fthread_freq_num\x18% \x01(\x03\x12%\n\tuser_list\x18\r \x03(\x0b\x32\x12.TiebaDesktop.User\"^\n\x0cPbPageResIdl\x12\"\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x13.TiebaDesktop.Error\x12*\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1c.TiebaDesktop.DataRes_PbPageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.PbPage.PbPageResIdl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATARES_PBPAGE._serialized_start=203
  _DATARES_PBPAGE._serialized_end=696
  _PBPAGERESIDL._serialized_start=698
  _PBPAGERESIDL._serialized_end=792
# @@protoc_insertion_point(module_scope)
