# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\Code\TiebaDesktop\resf\loading_amt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loadFlashForm(object):
    def setupUi(self, loadFlashForm):
        loadFlashForm.setObjectName("loadFlashForm")
        loadFlashForm.resize(534, 285)
        loadFlashForm.setStyleSheet("QWidget#loadFlashForm{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(loadFlashForm)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(loadFlashForm)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(loadFlashForm)
        QtCore.QMetaObject.connectSlotsByName(loadFlashForm)

    def retranslateUi(self, loadFlashForm):
        _translate = QtCore.QCoreApplication.translate
        loadFlashForm.setWindowTitle(_translate("loadFlashForm", "Form"))
        self.label_18.setText(_translate("loadFlashForm", "icon"))
        self.label_17.setText(_translate("loadFlashForm", "数据正在赶来的路上..."))
