# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\Code\TiebaDesktop\src\resf\messagebox.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_messageBox(object):
    def setupUi(self, messageBox):
        messageBox.setObjectName("messageBox")
        messageBox.resize(614, 390)
        font = QtGui.QFont()
        font.setPointSize(9)
        messageBox.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(messageBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.messageBoxIcon = QtWidgets.QLabel(messageBox)
        self.messageBoxIcon.setMinimumSize(QtCore.QSize(30, 0))
        self.messageBoxIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.messageBoxIcon.setObjectName("messageBoxIcon")
        self.verticalLayout.addWidget(self.messageBoxIcon)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.messageBoxTitle = QtWidgets.QLabel(messageBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.messageBoxTitle.setFont(font)
        self.messageBoxTitle.setWordWrap(True)
        self.messageBoxTitle.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.messageBoxTitle.setObjectName("messageBoxTitle")
        self.verticalLayout_2.addWidget(self.messageBoxTitle)
        self.messageBoxText = QtWidgets.QLabel(messageBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.messageBoxText.setFont(font)
        self.messageBoxText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.messageBoxText.setWordWrap(True)
        self.messageBoxText.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.messageBoxText.setObjectName("messageBoxText")
        self.verticalLayout_2.addWidget(self.messageBoxText)
        spacerItem1 = QtWidgets.QSpacerItem(5, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.messageBoxButtons = QtWidgets.QWidget(messageBox)
        self.messageBoxButtons.setObjectName("messageBoxButtons")
        self.gridLayout_2.addWidget(self.messageBoxButtons, 1, 0, 1, 1)

        self.retranslateUi(messageBox)
        QtCore.QMetaObject.connectSlotsByName(messageBox)

    def retranslateUi(self, messageBox):
        _translate = QtCore.QCoreApplication.translate
        messageBox.setWindowTitle(_translate("messageBox", "消息框"))
        self.messageBoxIcon.setText(_translate("messageBox", "icon"))
        self.messageBoxTitle.setText(_translate("messageBox", "title"))
        self.messageBoxText.setText(_translate("messageBox", "text"))
