# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\Code\TiebaDesktop\src\resf\tb_browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1215, 701)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setStyleSheet("/* 设置整个 QTabWidget 背景透明 */\n"
"QTabWidget {\n"
"    background: transparent;\n"
"    border: none;\n"
"    /* 关键：整体无边框 */\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    border: none;\n"
"    background: transparent;\n"
"    alignment: left;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    padding: 6px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"QTabBar::QToolButton {\n"
"    alignment: left;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    font: 9pt \"微软雅黑\";\n"
"    background: rgb(232, 232, 232);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    font: 9pt \"微软雅黑\";\n"
"    background: rgb(202, 202, 202);\n"
"}")
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.toolButton_2 = QtWidgets.QToolButton(self.frame)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout.addWidget(self.toolButton_2)
        self.toolButton_3 = QtWidgets.QToolButton(self.frame)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout.addWidget(self.toolButton_3)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.toolButton_5 = QtWidgets.QToolButton(self.frame)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout.addWidget(self.toolButton_5)
        self.toolButton_6 = QtWidgets.QToolButton(self.frame)
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout.addWidget(self.toolButton_6)
        self.toolButton_4 = QtWidgets.QToolButton(self.frame)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout.addWidget(self.toolButton_4)
        self.toolButton_7 = QtWidgets.QToolButton(self.frame)
        self.toolButton_7.setObjectName("toolButton_7")
        self.horizontalLayout.addWidget(self.toolButton_7)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "内置浏览器"))
        self.toolButton.setToolTip(_translate("Form", "<html><head/><body><p>后退</p></body></html>"))
        self.toolButton.setText(_translate("Form", "bk"))
        self.toolButton_2.setToolTip(_translate("Form", "<html><head/><body><p>前进</p></body></html>"))
        self.toolButton_2.setText(_translate("Form", "fw"))
        self.toolButton_3.setToolTip(_translate("Form", "<html><head/><body><p>刷新</p></body></html>"))
        self.toolButton_3.setText(_translate("Form", "rf"))
        self.lineEdit.setPlaceholderText(_translate("Form", "输入网址"))
        self.toolButton_5.setToolTip(_translate("Form", "<html><head/><body><p>在系统浏览器内打开</p></body></html>"))
        self.toolButton_5.setText(_translate("Form", "ob"))
        self.toolButton_6.setToolTip(_translate("Form", "<html><head/><body><p>在贴吧桌面中打开</p></body></html>"))
        self.toolButton_6.setText(_translate("Form", "oc"))
        self.toolButton_4.setToolTip(_translate("Form", "<html><head/><body><p>查看下载内容</p></body></html>"))
        self.toolButton_4.setText(_translate("Form", "dl"))
        self.toolButton_7.setToolTip(_translate("Form", "工具菜单"))
        self.toolButton_7.setText(_translate("Form", "mn"))
