# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\Code\TiebaDesktop\src\resf\tie_detail_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(854, 644)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form.setPalette(palette)
        Form.setStyleSheet("QWidget{font-family: \"微软雅黑\";}\n"
"")
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setContentsMargins(0, 7, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 854, 480))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollAreaWidgetContents.setPalette(palette)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setWordWrap(True)
        self.label_5.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setMinimumSize(QtCore.QSize(50, 20))
        self.label_13.setMaximumSize(QtCore.QSize(40, 25))
        self.label_13.setToolTip("")
        self.label_13.setStyleSheet("QLabel{\n"
"    background-color: rgb(91, 68, 200);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"}\n"
"")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setMinimumSize(QtCore.QSize(50, 20))
        self.label_12.setMaximumSize(QtCore.QSize(40, 25))
        self.label_12.setToolTip("")
        self.label_12.setStyleSheet("QLabel{\n"
"    background-color: rgb(91, 68, 200);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"}\n"
"")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setMinimumSize(QtCore.QSize(50, 20))
        self.label_8.setMaximumSize(QtCore.QSize(40, 25))
        self.label_8.setStyleSheet("QLabel{\n"
"    background-color: rgb(91, 68, 200);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"}\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setWordWrap(True)
        self.label_6.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 2, 1, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidget.setWordWrap(True)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_4.addWidget(self.listWidget, 3, 1, 1, 1)
        self.listWidget_4 = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_4.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_4.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_4.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_4.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidget_4.setWordWrap(True)
        self.listWidget_4.setObjectName("listWidget_4")
        self.gridLayout_4.addWidget(self.listWidget_4, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 6, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 2, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setMinimumSize(QtCore.QSize(40, 21))
        self.label_11.setMaximumSize(QtCore.QSize(40, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel{\n"
"    background-color: rgb(91, 68, 200);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"}\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setMinimumSize(QtCore.QSize(45, 21))
        self.label_10.setMaximumSize(QtCore.QSize(40, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel{\n"
"    background-color: rgb(91, 68, 200);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"}\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setMinimumSize(QtCore.QSize(45, 21))
        self.label_9.setMaximumSize(QtCore.QSize(40, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_9.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(101, 211, 171);\n"
"    border-radius: 7px;\n"
"}\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 2)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_5.addWidget(self.line_3)
        self.horizontalLayout_5.setStretch(1, 1)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 4, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 5, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setStyleSheet("QFrame{\n"
"    background-color: rgb(154, 154, 154);\n"
"    border-radius: 7px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_8.setContentsMargins(-1, 3, -1, 4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 0, 0, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.frame_3)
        self.toolButton_2.setStyleSheet("QToolButton {\n"
"                background-color: transparent;\n"
"                border: none;\n"
"                border-radius: 6px;\n"
"                padding: 1px;\n"
"                icon-size: 17px;\n"
"                }\n"
"\n"
"                /* 鼠标悬停时：轻微灰色背景 */\n"
"                QToolButton:hover {\n"
"                background-color: rgba(0, 0, 0, 0.1);\n"
"                }\n"
"\n"
"                /* 按下时：更深的背景色，模拟按下效果 */\n"
"                QToolButton:pressed {\n"
"                background-color: rgba(0, 0, 0, 0.24);\n"
"                }\n"
"\n"
"                /* 禁用状态：半透明，显示不可点击 */\n"
"                QToolButton:disabled {\n"
"                background-color: transparent;\n"
"                opacity: 0.4;\n"
"                }\n"
"\n"
"                /* 可选：如果按钮有菜单箭头，也可以美化箭头 */\n"
"                QToolButton::menu-indicator {\n"
"                subcontrol-position: right center;\n"
"                subcontrol-origin: padding;\n"
"                left: -4px;\n"
"                }")
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_8.addWidget(self.toolButton_2, 0, 2, 1, 1)
        self.gridLayout_8.setColumnStretch(1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 1, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 7, 0, 1, 1)
        self.verticalFrame = QtWidgets.QFrame(Form)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setContentsMargins(9, 1, 9, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.verticalFrame)
        self.frame.setStyleSheet("QFrame#frame{\n"
"    background-color: rgb(91, 68, 200);\n"
"    border-radius: 13px;\n"
"}\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setContentsMargins(9, 4, 9, 4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.spinBox = QtWidgets.QSpinBox(self.frame)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_6.addWidget(self.spinBox, 1, 3, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_6.addWidget(self.pushButton_8, 1, 9, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 1, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 1, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 1, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 1, 5, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setStyleSheet("QToolButton {\n"
"                background-color: transparent;\n"
"                border: none;\n"
"                border-radius: 6px;\n"
"                padding: 1px;\n"
"                icon-size: 17px;\n"
"                }\n"
"\n"
"                /* 鼠标悬停时：轻微灰色背景 */\n"
"                QToolButton:hover {\n"
"                background-color: rgba(0, 0, 0, 0.1);\n"
"                }\n"
"\n"
"                /* 按下时：更深的背景色，模拟按下效果 */\n"
"                QToolButton:pressed {\n"
"                background-color: rgba(0, 0, 0, 0.24);\n"
"                }\n"
"\n"
"                /* 禁用状态：半透明，显示不可点击 */\n"
"                QToolButton:disabled {\n"
"                background-color: transparent;\n"
"                opacity: 0.4;\n"
"                }\n"
"\n"
"                /* 可选：如果按钮有菜单箭头，也可以美化箭头 */\n"
"                QToolButton::menu-indicator {\n"
"                subcontrol-position: right center;\n"
"                subcontrol-origin: padding;\n"
"                left: -4px;\n"
"                }")
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_6.addWidget(self.toolButton, 1, 12, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_6.addWidget(self.pushButton_7, 1, 6, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_6.addWidget(self.pushButton_9, 1, 8, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.gridLayout_3.addWidget(self.verticalFrame, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(91, 68, 200);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 13px;\n"
"    text-align: right;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(115, 87, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(103, 32, 255);\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_4.addWidget(self.checkBox)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(25, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.frame1 = QtWidgets.QFrame(Form)
        self.frame1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame1.setObjectName("frame1")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame1)
        self.gridLayout_7.setContentsMargins(9, 1, 9, 9)
        self.gridLayout_7.setHorizontalSpacing(7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.textEdit = QtWidgets.QTextEdit(self.frame1)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.textEdit.setFont(font)
        self.textEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit.setAcceptRichText(False)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_7.addWidget(self.textEdit, 7, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame1)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_7.addWidget(self.pushButton_3, 7, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame1)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_5.addWidget(self.pushButton_5, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_5.addWidget(self.pushButton_6, 0, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_5.addWidget(self.pushButton_10, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.frame_2, 0, 1, 1, 2)
        self.gridLayout_3.addWidget(self.frame1, 8, 0, 1, 1)
        self.gridLayout_3.setRowStretch(7, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "贴子预览"))
        self.label_5.setText(_translate("Form", "数据加载中..."))
        self.label_13.setText(_translate("Form", "精华贴"))
        self.label_12.setText(_translate("Form", "置顶贴"))
        self.label_8.setToolTip(_translate("Form", "在求助贴下回贴，一次经验 +6。"))
        self.label_8.setText(_translate("Form", "求助贴"))
        self.label_2.setText(_translate("Form", "你已经到达了贴子的尽头"))
        self.label_11.setText(_translate("Form", "吧务"))
        self.label_10.setToolTip(_translate("Form", "该用户的贴吧成长等级"))
        self.label_10.setText(_translate("Form", "Lv.1"))
        self.label_9.setToolTip(_translate("Form", "该用户的吧等级，点击可查看头衔对照表"))
        self.label_9.setText(_translate("Form", "Lv.1"))
        self.label_7.setText(_translate("Form", "共 x 条回复"))
        self.label_20.setText(_translate("Form", "贴子内容提示"))
        self.label_19.setText(_translate("Form", "icon"))
        self.toolButton_2.setToolTip(_translate("Form", "关闭此提示"))
        self.toolButton_2.setText(_translate("Form", "x"))
        self.pushButton_8.setText(_translate("Form", "回首楼"))
        self.label_17.setText(_translate("Form", "页，共有x页"))
        self.label_16.setText(_translate("Form", "当前在第"))
        self.label_18.setText(_translate("Form", "跳页"))
        self.toolButton.setToolTip(_translate("Form", "关闭此悬浮条"))
        self.toolButton.setText(_translate("Form", "x"))
        self.pushButton_7.setText(_translate("Form", "立即跳转"))
        self.pushButton_9.setText(_translate("Form", "回上一页"))
        self.checkBox.setText(_translate("Form", "只看楼主"))
        self.comboBox.setItemText(0, _translate("Form", "正序"))
        self.comboBox.setItemText(1, _translate("Form", "倒序"))
        self.comboBox.setItemText(2, _translate("Form", "热门排序"))
        self.pushButton_4.setText(_translate("Form", "赞"))
        self.pushButton.setText(_translate("Form", "..."))
        self.textEdit.setPlaceholderText(_translate("Form", "来都来了，说两句吧"))
        self.pushButton_3.setText(_translate("Form", "发贴"))
        self.pushButton_5.setToolTip(_translate("Form", "向输入框内插入图片富文本标签。\n"
"将会在文本光标处插入富文本标签，如果选择了文本，那么选择的文本会被替换为富文本标签。"))
        self.pushButton_5.setText(_translate("Form", "图片"))
        self.pushButton_6.setToolTip(_translate("Form", "向输入框内插入提及信息富文本标签，可以通过该方法@他人。\n"
"将会在文本光标处插入富文本标签，如果选择了文本，那么选择的文本会被替换为富文本标签。"))
        self.pushButton_6.setText(_translate("Form", "@他人"))
        self.pushButton_10.setToolTip(_translate("Form", "向输入框内插入表情富文本标签，可以插入贴吧的黄豆表情。\n"
"将会在文本光标处插入富文本标签，如果选择了文本，那么选择的文本会被替换为富文本标签。"))
        self.pushButton_10.setText(_translate("Form", "表情"))
