# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Profile/ForumGodDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&proto/Profile/ForumGodDetailInfo.proto\x12\x0cTiebaDesktop\"\x90\x01\n\x12\x46orumGodDetailInfo\x12\x0e\n\x06god_id\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12\r\n\x05intro\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x65tail_intro\x18\x04 \x01(\t\x12\x10\n\x08\x66orum_id\x18\x05 \x01(\x03\x12\x12\n\nforum_name\x18\x06 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x07 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Profile.ForumGodDetailInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FORUMGODDETAILINFO._serialized_start=57
  _FORUMGODDETAILINFO._serialized_end=201
# @@protoc_insertion_point(module_scope)
