# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Profile/UserAgreeInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!proto/Profile/UserAgreeInfo.proto\x12\x0cTiebaDesktop\"\xa2\x01\n\rUserAgreeInfo\x12\x17\n\x0ftotal_agree_num\x18\x01 \x01(\x03\x12\x18\n\x10normal_agree_num\x18\x02 \x01(\x03\x12\x16\n\x0euser_agree_num\x18\x03 \x01(\x03\x12\x17\n\x0fvideo_agree_num\x18\x04 \x01(\x03\x12\x15\n\rala_agree_num\x18\x05 \x01(\x03\x12\x16\n\x0ehas_user_agree\x18\x06 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Profile.UserAgreeInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERAGREEINFO._serialized_start=52
  _USERAGREEINFO._serialized_end=214
# @@protoc_insertion_point(module_scope)
