# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/AccessState.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import UserSessionInfo_pb2 as proto_dot_UserSessionInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/AccessState.proto\x12\x0cTiebaDesktop\x1a\x1bproto/UserSessionInfo.proto\"[\n\x0b\x41\x63\x63\x65ssState\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12/\n\x08userinfo\x18\x03 \x01(\x0b\x32\x1d.TiebaDesktop.UserSessionInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.AccessState_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACCESSSTATE._serialized_start=70
  _ACCESSSTATE._serialized_end=161
# @@protoc_insertion_point(module_scope)
