# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Agree.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/Agree.proto\x12\x0cTiebaDesktop\"\x81\x01\n\x05\x41gree\x12\x11\n\tagree_num\x18\x01 \x01(\x03\x12\x11\n\thas_agree\x18\x02 \x01(\x05\x12\x12\n\nagree_type\x18\x03 \x01(\x05\x12\x14\n\x0c\x64isagree_num\x18\x04 \x01(\x03\x12\x16\n\x0e\x64iff_agree_num\x18\x05 \x01(\x03\x12\x10\n\x08lz_agree\x18\x06 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Agree_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AGREE._serialized_start=36
  _AGREE._serialized_end=165
# @@protoc_insertion_point(module_scope)
