# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Anti.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import BlockPopInfo_pb2 as proto_dot_BlockPopInfo__pb2
from proto import DelThreadText_pb2 as proto_dot_DelThreadText__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/Anti.proto\x12\x0cTiebaDesktop\x1a\x18proto/BlockPopInfo.proto\x1a\x19proto/DelThreadText.proto\"\xbd\x05\n\x04\x41nti\x12\x0b\n\x03tbs\x18\x01 \x01(\t\x12\x0e\n\x06ifpost\x18\x02 \x01(\x05\x12\x0f\n\x07ifposta\x18\x03 \x01(\x05\x12\x13\n\x0b\x66orbid_flag\x18\x04 \x01(\x05\x12\x13\n\x0b\x66orbid_info\x18\x05 \x01(\t\x12\x12\n\nblock_stat\x18\x06 \x01(\x05\x12\x11\n\thide_stat\x18\x07 \x01(\x05\x12\x12\n\nvcode_stat\x18\x08 \x01(\x05\x12\x13\n\x0b\x64\x61ys_tofree\x18\t \x01(\x05\x12\x12\n\nhas_chance\x18\n \x01(\x05\x12\x0f\n\x07ifvoice\x18\x0b \x01(\x05\x12\x15\n\rvoice_message\x18\x0c \x01(\t\x12\x12\n\nifaddition\x18\r \x01(\x05\x12\x12\n\nneed_vcode\x18\x0e \x01(\x05\x12\x11\n\tvcode_md5\x18\x0f \x01(\t\x12\x15\n\rvcode_pic_url\x18\x10 \x01(\t\x12\x11\n\tuser_mute\x18\x11 \x01(\t\x12\x12\n\nifxiaoying\x18\x12 \x01(\t\x12\x14\n\x0cpoll_message\x18\x13 \x01(\t\x12\x15\n\rvideo_message\x18\x14 \x01(\t\x12\x1b\n\x13video_local_message\x18\x15 \x01(\t\x12\x32\n\x0e\x62lock_pop_info\x18\x16 \x01(\x0b\x32\x1a.TiebaDesktop.BlockPopInfo\x12\x1a\n\x12reply_private_flag\x18\x17 \x01(\x05\x12\x34\n\x0f\x64\x65l_thread_text\x18\x18 \x03(\x0b\x32\x1b.TiebaDesktop.DelThreadText\x12\x17\n\x0fmulti_delthread\x18\x19 \x01(\x05\x12\x12\n\npoll_level\x18\x1a \x01(\r\x12\x11\n\tcan_goods\x18\x1b \x01(\x05\x12\x14\n\x0cis_sexyforum\x18\x1c \x01(\x08\x12\x19\n\x11teenmode_interval\x18\x1d \x01(\t\x12\x17\n\x0fuser_chat_block\x18\x1e \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Anti_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ANTI._serialized_start=88
  _ANTI._serialized_end=789
# @@protoc_insertion_point(module_scope)
