# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/BlockPopInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/BlockPopInfo.proto\x12\x0cTiebaDesktop\"\xc3\x01\n\x0c\x42lockPopInfo\x12\x10\n\x08\x63\x61n_post\x18\x01 \x01(\x05\x12\x12\n\nblock_info\x18\x02 \x01(\t\x12\x12\n\nahead_info\x18\x03 \x01(\t\x12\x11\n\tahead_url\x18\x04 \x01(\t\x12\x0f\n\x07ok_info\x18\x05 \x01(\t\x12\x12\n\nahead_type\x18\x06 \x01(\x05\x12\x15\n\rappeal_status\x18\x07 \x01(\x05\x12\x12\n\nappeal_msg\x18\x08 \x01(\t\x12\x16\n\x0esub_block_info\x18\x0b \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.BlockPopInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLOCKPOPINFO._serialized_start=43
  _BLOCKPOPINFO._serialized_end=238
# @@protoc_insertion_point(module_scope)
