# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/CommentPublisherConfig.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import PbPublisherBtnsConfig_pb2 as proto_dot_PbPublisherBtnsConfig__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"proto/CommentPublisherConfig.proto\x12\x0cTiebaDesktop\x1a!proto/PbPublisherBtnsConfig.proto\"\x8d\x01\n\x16\x43ommentPublisherConfig\x12\x38\n\x0b\x62ottom_btns\x18\x01 \x03(\x0b\x32#.TiebaDesktop.PbPublisherBtnsConfig\x12\x39\n\x0c\x63omment_btns\x18\x02 \x03(\x0b\x32#.TiebaDesktop.PbPublisherBtnsConfigb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.CommentPublisherConfig_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMENTPUBLISHERCONFIG._serialized_start=88
  _COMMENTPUBLISHERCONFIG._serialized_end=229
# @@protoc_insertion_point(module_scope)
