# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ContriInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import ToastConfig_pb2 as proto_dot_ToastConfig__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/ContriInfo.proto\x12\x0cTiebaDesktop\x1a\x17proto/ToastConfig.proto\"c\n\nContriInfo\x12\x11\n\tcolor_msg\x18\x01 \x01(\t\x12\x11\n\tafter_msg\x18\x02 \x01(\t\x12/\n\x0ctoast_config\x18\x03 \x03(\x0b\x32\x19.TiebaDesktop.ToastConfigb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ContriInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTRIINFO._serialized_start=65
  _CONTRIINFO._serialized_end=164
# @@protoc_insertion_point(module_scope)
