# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/HotTWThreadInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import User_pb2 as proto_dot_User__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/HotTWThreadInfo.proto\x12\x0cTiebaDesktop\x1a\x10proto/User.proto\"L\n\x0fHotTWThreadInfo\x12%\n\tuser_list\x18\x01 \x03(\x0b\x32\x12.TiebaDesktop.User\x12\x12\n\nfans_count\x18\x02 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.HotTWThreadInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOTTWTHREADINFO._serialized_start=63
  _HOTTWTHREADINFO._serialized_end=139
# @@protoc_insertion_point(module_scope)
