# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/LabelInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/LabelInfo.proto\x12\x0cTiebaDesktop\"c\n\tLabelInfo\x12\x10\n\x08labelHot\x18\x01 \x01(\x05\x12\x14\n\x0clabelContent\x18\x02 \x01(\t\x12\x0f\n\x07labelId\x18\x03 \x01(\t\x12\x0f\n\x07img_url\x18\x04 \x01(\t\x12\x0c\n\x04type\x18\x05 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.LabelInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LABELINFO._serialized_start=39
  _LABELINFO._serialized_end=138
# @@protoc_insertion_point(module_scope)
