# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ManagerElection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/ManagerElection.proto\x12\x0cTiebaDesktop\"\xf7\x01\n\x0fManagerElection\x12\x10\n\x08\x63\x61n_vote\x18\x01 \x01(\r\x12\x10\n\x08vote_num\x18\x02 \x01(\r\x12\x17\n\x0f\x62\x65gin_vote_time\x18\x03 \x01(\r\x12\x16\n\x0evote_condition\x18\x05 \x03(\t\x12\x11\n\ttail_text\x18\x06 \x01(\t\x12\x1a\n\x12is_show_distribute\x18\x07 \x01(\r\x12\x16\n\x0eremainder_time\x18\x08 \x01(\r\x12\x0e\n\x06status\x18\t \x01(\r\x12\x1c\n\x14vote_condition_title\x18\n \x03(\t\x12\x1a\n\x12vote_condition_pic\x18\x0b \x03(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ManagerElection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MANAGERELECTION._serialized_start=46
  _MANAGERELECTION._serialized_end=293
# @@protoc_insertion_point(module_scope)
