# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/PbPublisherBtnsConfig.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!proto/PbPublisherBtnsConfig.proto\x12\x0cTiebaDesktop\"5\n\x15PbPublisherBtnsConfig\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0e\n\x06schema\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.PbPublisherBtnsConfig_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PBPUBLISHERBTNSCONFIG._serialized_start=51
  _PBPUBLISHERBTNSCONFIG._serialized_end=104
# @@protoc_insertion_point(module_scope)
