# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Post.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import PbContent_pb2 as proto_dot_PbContent__pb2
from proto import SubPostList_pb2 as proto_dot_SubPostList__pb2
from proto import User_pb2 as proto_dot_User__pb2
from proto import Agree_pb2 as proto_dot_Agree__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/Post.proto\x12\x0cTiebaDesktop\x1a\x15proto/PbContent.proto\x1a\x17proto/SubPostList.proto\x1a\x10proto/User.proto\x1a\x11proto/Agree.proto\"\xf2\x06\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05\x66loor\x18\x03 \x01(\r\x12\x0c\n\x04time\x18\x04 \x01(\r\x12(\n\x07\x63ontent\x18\x05 \x03(\x0b\x32\x17.TiebaDesktop.PbContent\x12\x17\n\x0fsub_post_number\x18\r \x01(\r\x12\x11\n\tauthor_id\x18\x13 \x01(\x03\x12\x31\n\rsub_post_list\x18\x0f \x01(\x0b\x32\x1a.TiebaDesktop.Post.SubPost\x12\x33\n\tsignature\x18\x15 \x01(\x0b\x32 .TiebaDesktop.Post.SignatureData\x12\"\n\x06\x61uthor\x18\x17 \x01(\x0b\x32\x12.TiebaDesktop.User\x12\"\n\x05\x61gree\x18% \x01(\x0b\x32\x13.TiebaDesktop.Agree\x12\x0b\n\x03tid\x18. \x01(\x03\x12\x36\n\rcustom_figure\x18< \x01(\x0b\x32\x1f.TiebaDesktop.Post.CustomFigure\x12\x34\n\x0c\x63ustom_state\x18= \x01(\x0b\x32\x1e.TiebaDesktop.Post.CustomState\x12\x34\n\x0c\x63hat_content\x18N \x01(\x0b\x32\x1e.TiebaDesktop.Post.ChatContent\x12;\n\x10sprite_meme_info\x18O \x01(\x0b\x32!.TiebaDesktop.Post.SpriteMemeInfo\x1a;\n\x07SubPost\x12\x30\n\rsub_post_list\x18\x02 \x03(\x0b\x32\x19.TiebaDesktop.SubPostList\x1a\x83\x01\n\rSignatureData\x12\x42\n\x07\x63ontent\x18\x04 \x03(\x0b\x32\x31.TiebaDesktop.Post.SignatureData.SignatureContent\x1a.\n\x10SignatureContent\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x1a(\n\x0c\x43ustomFigure\x12\x18\n\x10\x62\x61\x63kground_value\x18\x03 \x01(\t\x1a\x1e\n\x0b\x43ustomState\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x1a\x1d\n\x0b\x43hatContent\x12\x0e\n\x06\x62ot_uk\x18\x01 \x01(\t\x1a!\n\x0eSpriteMemeInfo\x12\x0f\n\x07meme_id\x18\x01 \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Post_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POST._serialized_start=120
  _POST._serialized_end=1002
  _POST_SUBPOST._serialized_start=669
  _POST_SUBPOST._serialized_end=728
  _POST_SIGNATUREDATA._serialized_start=731
  _POST_SIGNATUREDATA._serialized_end=862
  _POST_SIGNATUREDATA_SIGNATURECONTENT._serialized_start=816
  _POST_SIGNATUREDATA_SIGNATURECONTENT._serialized_end=862
  _POST_CUSTOMFIGURE._serialized_start=864
  _POST_CUSTOMFIGURE._serialized_end=904
  _POST_CUSTOMSTATE._serialized_start=906
  _POST_CUSTOMSTATE._serialized_end=936
  _POST_CHATCONTENT._serialized_start=938
  _POST_CHATCONTENT._serialized_end=967
  _POST_SPRITEMEMEINFO._serialized_start=969
  _POST_SPRITEMEMEINFO._serialized_end=1002
# @@protoc_insertion_point(module_scope)
