# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/PostAntiInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import AccessState_pb2 as proto_dot_AccessState__pb2
from proto import VcodeExtra_pb2 as proto_dot_VcodeExtra__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/PostAntiInfo.proto\x12\x0cTiebaDesktop\x1a\x17proto/AccessState.proto\x1a\x16proto/VcodeExtra.proto\"\xcd\x02\n\x0cPostAntiInfo\x12/\n\x0c\x61\x63\x63\x65ss_state\x18\x01 \x01(\x0b\x32\x19.TiebaDesktop.AccessState\x12\x1a\n\x12\x63onfilter_hitwords\x18\x02 \x03(\t\x12\x12\n\nneed_vcode\x18\x03 \x01(\t\x12\x11\n\tvcode_md5\x18\x04 \x01(\t\x12\x17\n\x0fvcode_prev_type\x18\x05 \x01(\t\x12\x12\n\nvcode_type\x18\x06 \x01(\t\x12\x12\n\npass_token\x18\x07 \x01(\t\x12\x15\n\rblock_content\x18\x08 \x01(\t\x12\x14\n\x0c\x62lock_cancel\x18\t \x01(\t\x12\x15\n\rblock_confirm\x18\n \x01(\t\x12\x15\n\rvcode_pic_url\x18\x0c \x01(\t\x12-\n\x0bvcode_extra\x18\r \x01(\x0b\x32\x18.TiebaDesktop.VcodeExtrab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.PostAntiInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSTANTIINFO._serialized_start=92
  _POSTANTIINFO._serialized_end=425
# @@protoc_insertion_point(module_scope)
