# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ReplyExp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/ReplyExp.proto\x12\x0cTiebaDesktop\"\xaa\x01\n\x08ReplyExp\x12\x0f\n\x07pre_msg\x18\x01 \x01(\t\x12\x11\n\tcolor_msg\x18\x02 \x01(\t\x12\x1d\n\x15\x63urrent_level_max_exp\x18\x03 \x01(\t\x12\x15\n\rcurrent_level\x18\x04 \x01(\t\x12\x0b\n\x03old\x18\x05 \x01(\t\x12\x0b\n\x03inc\x18\x06 \x01(\t\x12\x14\n\x0cquestion_msg\x18\x07 \x01(\t\x12\x14\n\x0cquestion_exp\x18\x08 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ReplyExp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REPLYEXP._serialized_start=39
  _REPLYEXP._serialized_end=209
# @@protoc_insertion_point(module_scope)
