# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ScoreLevelLimit.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/ScoreLevelLimit.proto\x12\x0cTiebaDesktop\"M\n\x0fScoreLevelLimit\x12\x19\n\x11score_level_limit\x18\x01 \x01(\x05\x12\x1f\n\x17score_level_limit_toast\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ScoreLevelLimit_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCORELEVELLIMIT._serialized_start=45
  _SCORELEVELLIMIT._serialized_end=122
# @@protoc_insertion_point(module_scope)
