# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/SimpleForum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/SimpleForum.proto\x12\x0cTiebaDesktop\"\x88\x02\n\x0bSimpleForum\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tis_exists\x18\x03 \x01(\x05\x12\x0e\n\x06\x61vatar\x18\x04 \x01(\t\x12\x10\n\x08is_liked\x18\x05 \x01(\r\x12\x11\n\tis_signed\x18\x06 \x01(\r\x12\x13\n\x0b\x66irst_class\x18\x07 \x01(\t\x12\x14\n\x0csecond_class\x18\x08 \x01(\t\x12\x0b\n\x03\x65xt\x18\t \x01(\t\x12\x10\n\x08level_id\x18\n \x01(\r\x12\x12\n\nmember_num\x18\x0c \x01(\x05\x12\x10\n\x08post_num\x18\r \x01(\x05\x12\x15\n\rrecommend_tip\x18\x14 \x01(\t\x12\x10\n\x08pendants\x18\x15 \x03(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.SimpleForum_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIMPLEFORUM._serialized_start=42
  _SIMPLEFORUM._serialized_end=306
# @@protoc_insertion_point(module_scope)
