# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ThemeColorInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import ThemeElement_pb2 as proto_dot_ThemeElement__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/ThemeColorInfo.proto\x12\x0cTiebaDesktop\x1a\x18proto/ThemeElement.proto\"\x8e\x01\n\x0eThemeColorInfo\x12\'\n\x03\x64\x61y\x18\x01 \x01(\x0b\x32\x1a.TiebaDesktop.ThemeElement\x12)\n\x05night\x18\x02 \x01(\x0b\x32\x1a.TiebaDesktop.ThemeElement\x12(\n\x04\x64\x61rk\x18\x03 \x01(\x0b\x32\x1a.TiebaDesktop.ThemeElementb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ThemeColorInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _THEMECOLORINFO._serialized_start=71
  _THEMECOLORINFO._serialized_end=213
# @@protoc_insertion_point(module_scope)
