# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ThemeElement.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/ThemeElement.proto\x12\x0cTiebaDesktop\"\xc6\x03\n\x0cThemeElement\x12\x14\n\x0c\x63ommon_color\x18\x01 \x01(\t\x12\x12\n\ndark_color\x18\x02 \x01(\t\x12\x13\n\x0blight_color\x18\x03 \x01(\t\x12\x15\n\rpattern_image\x18\x04 \x01(\t\x12\x12\n\nfont_color\x18\x05 \x01(\t\x12\x1c\n\x14pattern_image_height\x18\x06 \x01(\x03\x12\x1b\n\x13pattern_image_width\x18\x07 \x01(\x03\x12\x14\n\x0cpattern_text\x18\x08 \x01(\t\x12\x0c\n\x04type\x18\t \x01(\x05\x12\x13\n\x0bpattern_num\x18\n \x01(\x05\x12\x1c\n\x14pattern_image_select\x18\x0b \x01(\t\x12\"\n\x1apattern_image_not_selected\x18\x0c \x01(\t\x12\x12\n\ncover_type\x18\r \x01(\x05\x12\x15\n\ranimation_url\x18\x0e \x01(\t\x12\x1c\n\x14\x61ssist_animation_url\x18\x0f \x01(\t\x12\x1a\n\x12support_long_click\x18\x10 \x01(\x05\x12!\n\x19long_click_animation_urls\x18\x11 \x03(\t\x12\x0e\n\x06schema\x18\x12 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ThemeElement_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _THEMEELEMENT._serialized_start=43
  _THEMEELEMENT._serialized_end=497
# @@protoc_insertion_point(module_scope)
