# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ThreadScoreInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import ScoreLevelLimit_pb2 as proto_dot_ScoreLevelLimit__pb2
from proto import ThreadScoreItem_pb2 as proto_dot_ThreadScoreItem__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/ThreadScoreInfo.proto\x12\x0cTiebaDesktop\x1a\x1bproto/ScoreLevelLimit.proto\x1a\x1bproto/ThreadScoreItem.proto\"\xda\x01\n\x0fThreadScoreInfo\x12\x19\n\x11total_items_count\x18\x01 \x01(\r\x12,\n\x05items\x18\x02 \x03(\x0b\x32\x1d.TiebaDesktop.ThreadScoreItem\x12\x18\n\x10total_user_count\x18\x03 \x01(\x04\x12\x12\n\nshow_index\x18\x04 \x01(\r\x12\x38\n\x11score_level_limit\x18\x05 \x01(\x0b\x32\x1d.TiebaDesktop.ScoreLevelLimit\x12\x16\n\x0escore_item_ids\x18\x06 \x03(\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ThreadScoreInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _THREADSCOREINFO._serialized_start=104
  _THREADSCOREINFO._serialized_end=322
# @@protoc_insertion_point(module_scope)
