# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ThreadScoreItem.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import FeedKV_pb2 as proto_dot_FeedKV__pb2
from proto import Post_pb2 as proto_dot_Post__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/ThreadScoreItem.proto\x12\x0cTiebaDesktop\x1a\x12proto/FeedKV.proto\x1a\x10proto/Post.proto\"\x86\x02\n\x0fThreadScoreItem\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0b\n\x03pic\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\'\n\x0bhot_comment\x18\x05 \x01(\x0b\x32\x12.TiebaDesktop.Post\x12,\n\x0escore_user_num\x18\x06 \x03(\x0b\x32\x14.TiebaDesktop.FeedKV\x12\x16\n\x0etotal_user_num\x18\x07 \x01(\x04\x12\x11\n\tavg_score\x18\x08 \x01(\t\x12\x10\n\x08my_score\x18\t \x01(\r\x12&\n\nmy_comment\x18\n \x01(\x0b\x32\x12.TiebaDesktop.Postb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ThreadScoreItem_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _THREADSCOREITEM._serialized_start=84
  _THREADSCOREITEM._serialized_end=346
# @@protoc_insertion_point(module_scope)
