# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ThreadEasterEgg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import ShareInfo_pb2 as proto_dot_ShareInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/ThreadEasterEgg.proto\x12\x0cTiebaDesktop\x1a\x15proto/ShareInfo.proto\"\x8e\x01\n\x0fThreadEasterEgg\x12\x13\n\x0b\x61\x63tivity_id\x18\x01 \x01(\t\x12\x11\n\tvideo_url\x18\x02 \x01(\t\x12\x10\n\x08pop_text\x18\x03 \x01(\t\x12\x14\n\x0cpop_imageurl\x18\x04 \x01(\t\x12+\n\nshare_info\x18\x05 \x01(\x0b\x32\x17.TiebaDesktop.ShareInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ThreadEasterEgg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _THREADEASTEREGG._serialized_start=69
  _THREADEASTEREGG._serialized_end=211
# @@protoc_insertion_point(module_scope)
