# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Toast.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import FeedKV_pb2 as proto_dot_FeedKV__pb2
from proto import JumpText_pb2 as proto_dot_JumpText__pb2
from proto import ToastContent_pb2 as proto_dot_ToastContent__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/Toast.proto\x12\x0cTiebaDesktop\x1a\x12proto/FeedKV.proto\x1a\x14proto/JumpText.proto\x1a\x18proto/ToastContent.proto\"\xea\x03\n\x05Toast\x12\x11\n\ticon_type\x18\x01 \x01(\x05\x12+\n\x07\x63ontent\x18\x02 \x03(\x0b\x32\x1a.TiebaDesktop.ToastContent\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x12\n\nbackground\x18\x04 \x01(\t\x12\x10\n\x08icon_url\x18\x05 \x01(\t\x12\x15\n\ricon_url_dark\x18\x06 \x01(\t\x12\x10\n\x08task_ids\x18\x07 \x03(\x05\x12\x12\n\nicon_width\x18\x08 \x01(\x05\x12\x13\n\x0bicon_height\x18\t \x01(\x05\x12\x11\n\thud_width\x18\n \x01(\x05\x12\x0e\n\x06scheme\x18\x0b \x01(\t\x12\x15\n\ris_limit_page\x18\x0c \x01(\r\x12\x0c\n\x04type\x18\r \x01(\x05\x12/\n\x0bsub_content\x18\x0e \x03(\x0b\x32\x1a.TiebaDesktop.ToastContent\x12\x12\n\ndelay_time\x18\x0f \x01(\x05\x12\x0e\n\x06locate\x18\x10 \x01(\x05\x12+\n\x0b\x62utton_info\x18\x11 \x01(\x0b\x32\x16.TiebaDesktop.JumpText\x12\'\n\tlog_param\x18\x12 \x03(\x0b\x32\x14.TiebaDesktop.FeedKV\x12\x10\n\x08\x64uration\x18\x13 \x01(\x05\x12\x17\n\x0f\x62\x61\x63kground_dark\x18\x14 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Toast_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOAST._serialized_start=104
  _TOAST._serialized_end=594
# @@protoc_insertion_point(module_scope)
