# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ToastContent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/ToastContent.proto\x12\x0cTiebaDesktop\"\\\n\x0cToastContent\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\thas_color\x18\x02 \x01(\x05\x12\x12\n\ntext_color\x18\x03 \x01(\t\x12\x17\n\x0ftext_color_dark\x18\x04 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ToastContent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOASTCONTENT._serialized_start=42
  _TOASTCONTENT._serialized_end=134
# @@protoc_insertion_point(module_scope)
