# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/VcodeExtra.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/VcodeExtra.proto\x12\x0cTiebaDesktop\"l\n\nVcodeExtra\x12\x0f\n\x07textimg\x18\x01 \x01(\t\x12\x10\n\x08slideimg\x18\x02 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x03 \x01(\t\x12\x12\n\nsuccessimg\x18\x04 \x01(\t\x12\x15\n\rslideendpoint\x18\x05 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.VcodeExtra_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VCODEEXTRA._serialized_start=40
  _VCODEEXTRA._serialized_end=148
# @@protoc_insertion_point(module_scope)
