# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/VcodeInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import VcodeExtra_pb2 as proto_dot_VcodeExtra__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/VcodeInfo.proto\x12\x0cTiebaDesktop\x1a\x16proto/VcodeExtra.proto\"x\n\tVcodeInfo\x12\x11\n\tvcode_md5\x18\x01 \x01(\t\x12\x15\n\rvcode_pic_url\x18\x02 \x01(\t\x12\x12\n\nvcode_type\x18\x03 \x01(\t\x12-\n\x0bvcode_extra\x18\x04 \x01(\x0b\x32\x18.TiebaDesktop.VcodeExtrab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.VcodeInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VCODEINFO._serialized_start=63
  _VCODEINFO._serialized_end=183
# @@protoc_insertion_point(module_scope)
