# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/VideoInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/VideoInfo.proto\x12\x0cTiebaDesktop\"\xc1\x03\n\tVideoInfo\x12\x11\n\tvideo_md5\x18\x01 \x01(\t\x12\x11\n\tvideo_url\x18\x02 \x01(\t\x12\x16\n\x0evideo_duration\x18\x03 \x01(\r\x12\x13\n\x0bvideo_width\x18\x04 \x01(\r\x12\x14\n\x0cvideo_height\x18\x05 \x01(\r\x12\x15\n\rthumbnail_url\x18\x06 \x01(\t\x12\x17\n\x0fthumbnail_width\x18\x07 \x01(\r\x12\x18\n\x10thumbnail_height\x18\x08 \x01(\r\x12\x14\n\x0cvideo_length\x18\t \x01(\x05\x12\x12\n\nplay_count\x18\n \x01(\x05\x12\x16\n\x0emedia_subtitle\x18\x0b \x01(\t\x12\x19\n\x11video_select_flag\x18\r \x01(\x05\x12\x12\n\nvideo_type\x18\x0e \x01(\r\x12\x13\n\x0bis_vertical\x18\x0f \x01(\r\x12\x15\n\rmcn_lead_page\x18\x11 \x01(\t\x12\x13\n\x0bwth_mid_loc\x18\x13 \x01(\x01\x12\x13\n\x0bhth_mid_loc\x18\x14 \x01(\x01\x12\x1b\n\x13small_thumbnail_url\x18\x15 \x01(\t\x12\x1d\n\x15\x66irst_frame_thumbnail\x18\x16 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.VideoInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIDEOINFO._serialized_start=40
  _VIDEOINFO._serialized_end=489
# @@protoc_insertion_point(module_scope)
