# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Zan.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import User_pb2 as proto_dot_User__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/Zan.proto\x12\x0cTiebaDesktop\x1a\x10proto/User.proto\"\x87\x01\n\x03Zan\x12\x0b\n\x03num\x18\x01 \x01(\x05\x12&\n\nliker_list\x18\x02 \x03(\x0b\x32\x12.TiebaDesktop.User\x12\x10\n\x08is_liked\x18\x03 \x01(\x05\x12\x11\n\tlast_time\x18\x04 \x01(\x05\x12\x10\n\x08liker_id\x18\x05 \x03(\x03\x12\x14\n\x0c\x63onsent_type\x18\x06 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Zan_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ZAN._serialized_start=52
  _ZAN._serialized_end=187
# @@protoc_insertion_point(module_scope)
