# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ZhiBoInfoTW.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import HotTWThreadInfo_pb2 as proto_dot_HotTWThreadInfo__pb2
from proto import LabelInfo_pb2 as proto_dot_LabelInfo__pb2
from proto import NoticeInfo_pb2 as proto_dot_NoticeInfo__pb2
from proto import User_pb2 as proto_dot_User__pb2
from proto import Zan_pb2 as proto_dot_Zan__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/ZhiBoInfoTW.proto\x12\x0cTiebaDesktop\x1a\x1bproto/HotTWThreadInfo.proto\x1a\x15proto/LabelInfo.proto\x1a\x16proto/NoticeInfo.proto\x1a\x10proto/User.proto\x1a\x0fproto/Zan.proto\"\xb6\x04\n\x0bZhiBoInfoTW\x12\x11\n\tthread_id\x18\x01 \x01(\x04\x12\x15\n\rlivecover_src\x18\x02 \x01(\t\x12\x1b\n\x13livecover_src_bsize\x18\x03 \x01(\t\x12\x10\n\x08post_num\x18\x04 \x01(\r\x12\x11\n\treply_num\x18\x05 \x01(\r\x12\x1e\n\x03zan\x18\x06 \x01(\x0b\x32\x11.TiebaDesktop.Zan\x12\x12\n\nforum_name\x18\x07 \x01(\t\x12\x10\n\x08\x66orum_id\x18\x08 \x01(\x04\x12\x1a\n\x12last_modified_time\x18\t \x01(\x04\x12\r\n\x05title\x18\n \x01(\t\x12\x0f\n\x07\x63ontent\x18\x0b \x01(\t\x12 \n\x04user\x18\x0c \x01(\x0b\x32\x12.TiebaDesktop.User\x12\x32\n\x0bhot_tw_info\x18\r \x01(\x0b\x32\x1d.TiebaDesktop.HotTWThreadInfo\x12*\n\tlabelInfo\x18\x0e \x03(\x0b\x32\x17.TiebaDesktop.LabelInfo\x12\x1c\n\x14livecover_src_status\x18\x0f \x01(\t\x12-\n\x0bnotice_info\x18\x10 \x01(\x0b\x32\x18.TiebaDesktop.NoticeInfo\x12\x13\n\x0bis_headline\x18\x11 \x01(\x05\x12\x10\n\x08\x66req_num\x18\x13 \x01(\r\x12\x19\n\x11\x63opythread_remind\x18\x14 \x01(\r\x12\x16\n\x0eis_copytwzhibo\x18\x15 \x01(\r\x12\x10\n\x08\x66ield_ex\x18\x16 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ZhiBoInfoTW_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ZHIBOINFOTW._serialized_start=153
  _ZHIBOINFOTW._serialized_end=719
# @@protoc_insertion_point(module_scope)
