# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Profile/ProfileResIdl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import Error_pb2 as proto_dot_Error__pb2
from proto import Anti_pb2 as proto_dot_Anti__pb2
from proto import User_pb2 as proto_dot_User__pb2
from proto.Profile import UserGodInfo_pb2 as proto_dot_Profile_dot_UserGodInfo__pb2
from proto.Profile import UserAgreeInfo_pb2 as proto_dot_Profile_dot_UserAgreeInfo__pb2
from proto.Profile import NicknameInfo_pb2 as proto_dot_Profile_dot_NicknameInfo__pb2
from proto.Profile import MemberBlockInfo_pb2 as proto_dot_Profile_dot_MemberBlockInfo__pb2
from proto.Profile import VipBanner_pb2 as proto_dot_Profile_dot_VipBanner__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!proto/Profile/ProfileResIdl.proto\x12\x0cTiebaDesktop\x1a\x11proto/Error.proto\x1a\x10proto/Anti.proto\x1a\x10proto/User.proto\x1a\x1fproto/Profile/UserGodInfo.proto\x1a!proto/Profile/UserAgreeInfo.proto\x1a proto/Profile/NicknameInfo.proto\x1a#proto/Profile/MemberBlockInfo.proto\x1a\x1dproto/Profile/VipBanner.proto\"\xed\x02\n\x0f\x44\x61taRes_Profile\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.TiebaDesktop.User\x12%\n\tanti_stat\x18\x02 \x01(\x0b\x32\x12.TiebaDesktop.Anti\x12\x30\n\ruser_god_info\x18\x05 \x01(\x0b\x32\x19.TiebaDesktop.UserGodInfo\x12\x34\n\x0fuser_agree_info\x18\x0e \x01(\x0b\x32\x1b.TiebaDesktop.UserAgreeInfo\x12\x31\n\rnickname_info\x18\x11 \x01(\x0b\x32\x1a.TiebaDesktop.NicknameInfo\x12\x16\n\x0eis_black_white\x18\x1d \x01(\x05\x12\x31\n\nblock_info\x18$ \x01(\x0b\x32\x1d.TiebaDesktop.MemberBlockInfo\x12+\n\nvip_banner\x18\' \x01(\x0b\x32\x17.TiebaDesktop.VipBanner\"`\n\rProfileResIdl\x12\"\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x13.TiebaDesktop.Error\x12+\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1d.TiebaDesktop.DataRes_Profileb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Profile.ProfileResIdl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATARES_PROFILE._serialized_start=277
  _DATARES_PROFILE._serialized_end=642
  _PROFILERESIDL._serialized_start=644
  _PROFILERESIDL._serialized_end=740
# @@protoc_insertion_point(module_scope)
