# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Profile/UserGodInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.Profile import ForumGodDetailInfo_pb2 as proto_dot_Profile_dot_ForumGodDetailInfo__pb2
from proto.Profile import GodDetailInfo_pb2 as proto_dot_Profile_dot_GodDetailInfo__pb2
from proto import ThreadInfo_pb2 as proto_dot_ThreadInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto/Profile/UserGodInfo.proto\x12\x0cTiebaDesktop\x1a&proto/Profile/ForumGodDetailInfo.proto\x1a!proto/Profile/GodDetailInfo.proto\x1a\x16proto/ThreadInfo.proto\"\x8a\x02\n\x0bUserGodInfo\x12\x10\n\x08god_type\x18\x01 \x01(\x05\x12-\n\x08god_info\x18\x02 \x01(\x0b\x32\x1b.TiebaDesktop.GodDetailInfo\x12\x38\n\x0e\x66orum_god_list\x18\x03 \x03(\x0b\x32 .TiebaDesktop.ForumGodDetailInfo\x12\x0b\n\x03sex\x18\x04 \x01(\x05\x12\x0b\n\x03\x61ge\x18\x05 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x06 \x01(\t\x12-\n\x0bthread_list\x18\x07 \x03(\x0b\x32\x18.TiebaDesktop.ThreadInfo\x12\x10\n\x08\x63ur_page\x18\x08 \x01(\x05\x12\x14\n\x0ctotal_thread\x18\t \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Profile.UserGodInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERGODINFO._serialized_start=149
  _USERGODINFO._serialized_end=415
# @@protoc_insertion_point(module_scope)
