# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Media.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/Media.proto\x12\x0cTiebaDesktop\"\xe5\x03\n\x05Media\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x11\n\tsmall_pic\x18\x02 \x01(\t\x12\x0f\n\x07\x62ig_pic\x18\x03 \x01(\t\x12\x11\n\twater_pic\x18\x04 \x01(\t\x12\x0c\n\x04vpic\x18\x05 \x01(\t\x12\x0c\n\x04vsrc\x18\x06 \x01(\t\x12\r\n\x05vhsrc\x18\x07 \x01(\t\x12\x0f\n\x07src_pic\x18\x08 \x01(\t\x12\x0c\n\x04text\x18\t \x01(\t\x12\r\n\x05width\x18\n \x01(\r\x12\x0e\n\x06height\x18\x0b \x01(\r\x12\r\n\x05\x62size\x18\x0c \x01(\t\x12\x13\n\x0b\x64uring_time\x18\r \x01(\r\x12\x0e\n\x06\x65_type\x18\x0e \x01(\r\x12\x12\n\norigin_pic\x18\x0f \x01(\t\x12\x13\n\x0borigin_size\x18\x10 \x01(\r\x12\x0f\n\x07post_id\x18\x11 \x01(\x03\x12\x13\n\x0b\x64ynamic_pic\x18\x12 \x01(\t\x12\x13\n\x0bis_long_pic\x18\x13 \x01(\r\x12\x19\n\x11show_original_btn\x18\x14 \x01(\r\x12\x16\n\x0eis_blocked_pic\x18\x15 \x01(\r\x12\x13\n\x0bwth_mid_loc\x18\x16 \x01(\x01\x12\x13\n\x0bhth_mid_loc\x18\x17 \x01(\x01\x12\x10\n\x08jump_url\x18\x18 \x01(\t\x12\x12\n\nguide_text\x18\x19 \x01(\t\x12\x13\n\x0blottie_type\x18\x1a \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Media_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEDIA._serialized_start=36
  _MEDIA._serialized_end=521
# @@protoc_insertion_point(module_scope)
