# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/PbContent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/PbContent.proto\x12\x0cTiebaDesktop\"\xc7\x05\n\tPbContent\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0c\n\x04link\x18\x03 \x01(\t\x12\x0b\n\x03src\x18\x04 \x01(\t\x12\r\n\x05\x62size\x18\x05 \x01(\t\x12\x0f\n\x07\x62ig_src\x18\x06 \x01(\t\x12\x10\n\x08\x62ig_size\x18\x07 \x01(\t\x12\x0f\n\x07\x63\x64n_src\x18\x08 \x01(\t\x12\x13\n\x0b\x62ig_cdn_src\x18\t \x01(\t\x12\x0f\n\x07imgtype\x18\n \x01(\t\x12\t\n\x01\x63\x18\x0b \x01(\t\x12\x11\n\tvoice_md5\x18\x0c \x01(\t\x12\x13\n\x0b\x64uring_time\x18\r \x01(\r\x12\x0e\n\x06is_sub\x18\x0e \x01(\r\x12\x0b\n\x03uid\x18\x0f \x01(\x03\x12\x0f\n\x07\x64ynamic\x18\x10 \x01(\t\x12\x0f\n\x07_static\x18\x11 \x01(\t\x12\r\n\x05width\x18\x12 \x01(\r\x12\x0e\n\x06height\x18\x13 \x01(\r\x12\x13\n\x0bpacket_name\x18\x14 \x01(\t\x12\x11\n\tphonetype\x18\x15 \x01(\t\x12\x15\n\ris_native_app\x18\x16 \x01(\r\x12\x0e\n\x06\x65_type\x18\x18 \x01(\r\x12\x12\n\norigin_src\x18\x19 \x01(\t\x12\x10\n\x08\x62tn_type\x18\x1a \x01(\r\x12\x13\n\x0borigin_size\x18\x1b \x01(\r\x12\r\n\x05\x63ount\x18\x1c \x01(\x05\x12\x16\n\x0emedia_subtitle\x18\x1f \x01(\t\x12\x10\n\x08url_type\x18  \x01(\x05\x12\x13\n\x0bis_long_pic\x18\" \x01(\r\x12\x19\n\x11show_original_btn\x18# \x01(\r\x12\x16\n\x0e\x63\x64n_src_active\x18$ \x01(\t\x12\x1a\n\x12topic_special_icon\x18% \x01(\t\x12\x0f\n\x07item_id\x18& \x01(\x04\x12\x17\n\x0fitem_forum_name\x18\' \x01(\t\x12\x0e\n\x06pic_id\x18* \x01(\x03\x12\x11\n\tlink_type\x18+ \x01(\x05\x12\x15\n\rtarget_scheme\x18, \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.PbContent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PBCONTENT._serialized_start=40
  _PBCONTENT._serialized_end=751
# @@protoc_insertion_point(module_scope)
