# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/PermissionList.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/PermissionList.proto\x12\x0cTiebaDesktop\"@\n\x0ePermissionList\x12\x0e\n\x06\x66ollow\x18\x01 \x01(\x05\x12\x10\n\x08interact\x18\x02 \x01(\x05\x12\x0c\n\x04\x63hat\x18\x03 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.PermissionList_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERMISSIONLIST._serialized_start=44
  _PERMISSIONLIST._serialized_end=108
# @@protoc_insertion_point(module_scope)
