# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/PollInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import PollOption_pb2 as proto_dot_PollOption__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/PollInfo.proto\x12\x0cTiebaDesktop\x1a\x16proto/PollOption.proto\"\x8e\x02\n\x08PollInfo\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x10\n\x08is_multi\x18\x02 \x01(\x05\x12\x11\n\ttotal_num\x18\x03 \x01(\x03\x12\x15\n\roptions_count\x18\x04 \x01(\x05\x12\x11\n\tis_polled\x18\x05 \x01(\x05\x12\x14\n\x0cpolled_value\x18\x06 \x01(\t\x12\x0c\n\x04tips\x18\x07 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x08 \x01(\x05\x12)\n\x07options\x18\t \x03(\x0b\x32\x18.TiebaDesktop.PollOption\x12\x0e\n\x06status\x18\n \x01(\x05\x12\x12\n\ntotal_poll\x18\x0b \x01(\x03\x12\r\n\x05title\x18\x0c \x01(\t\x12\x11\n\tlast_time\x18\r \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.PollInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POLLINFO._serialized_start=63
  _POLLINFO._serialized_end=333
# @@protoc_insertion_point(module_scope)
