# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/SubPostList.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import Agree_pb2 as proto_dot_Agree__pb2
from proto import PbContent_pb2 as proto_dot_PbContent__pb2
from proto import User_pb2 as proto_dot_User__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/SubPostList.proto\x12\x0cTiebaDesktop\x1a\x11proto/Agree.proto\x1a\x15proto/PbContent.proto\x1a\x10proto/User.proto\"\x8c\x02\n\x0bSubPostList\x12\n\n\x02id\x18\x01 \x01(\x04\x12(\n\x07\x63ontent\x18\x02 \x03(\x0b\x32\x17.TiebaDesktop.PbContent\x12\x0c\n\x04time\x18\x03 \x01(\r\x12\x11\n\tauthor_id\x18\x04 \x01(\x03\x12\r\n\x05title\x18\x05 \x01(\t\x12\r\n\x05\x66loor\x18\x06 \x01(\r\x12\"\n\x06\x61uthor\x18\x07 \x01(\x0b\x32\x12.TiebaDesktop.User\x12\x13\n\x0bis_giftpost\x18\x08 \x01(\x05\x12\"\n\x05\x61gree\x18\t \x01(\x0b\x32\x13.TiebaDesktop.Agree\x12\x13\n\x0bis_fake_top\x18\x0b \x01(\x05\x12\x16\n\x0eis_author_view\x18\x0c \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.SubPostList_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUBPOSTLIST._serialized_start=102
  _SUBPOSTLIST._serialized_end=370
# @@protoc_insertion_point(module_scope)
