# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/GetUserBlackInfo/GetUserBlackInfoReqIdl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import CommonReq_pb2 as proto_dot_CommonReq__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3proto/GetUserBlackInfo/GetUserBlackInfoReqIdl.proto\x12\x0cTiebaDesktop\x1a\x15proto/CommonReq.proto\"V\n\x18\x44\x61taReq_GetUserBlackInfo\x12\'\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x17.TiebaDesktop.CommonReq\x12\x11\n\tblack_uid\x18\x02 \x01(\x03\"N\n\x16GetUserBlackInfoReqIdl\x12\x34\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32&.TiebaDesktop.DataReq_GetUserBlackInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.GetUserBlackInfo.GetUserBlackInfoReqIdl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATAREQ_GETUSERBLACKINFO._serialized_start=92
  _DATAREQ_GETUSERBLACKINFO._serialized_end=178
  _GETUSERBLACKINFOREQIDL._serialized_start=180
  _GETUSERBLACKINFOREQIDL._serialized_end=258
# @@protoc_insertion_point(module_scope)
