# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/AddPost/AddPostResIdl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import Error_pb2 as proto_dot_Error__pb2
from proto.AddPost import DrawThreadPopUp_pb2 as proto_dot_AddPost_dot_DrawThreadPopUp__pb2
from proto.AddPost import PostScoreInfo_pb2 as proto_dot_AddPost_dot_PostScoreInfo__pb2
from proto import Anti_pb2 as proto_dot_Anti__pb2
from proto import ContriInfo_pb2 as proto_dot_ContriInfo__pb2
from proto import IconStampInfo_pb2 as proto_dot_IconStampInfo__pb2
from proto import PostAntiInfo_pb2 as proto_dot_PostAntiInfo__pb2
from proto import ReplyExp_pb2 as proto_dot_ReplyExp__pb2
from proto import TbInteraction_pb2 as proto_dot_TbInteraction__pb2
from proto import Toast_pb2 as proto_dot_Toast__pb2
from proto import VcodeInfo_pb2 as proto_dot_VcodeInfo__pb2
from proto import ZhiBoInfoTW_pb2 as proto_dot_ZhiBoInfoTW__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!proto/AddPost/AddPostResIdl.proto\x12\x0cTiebaDesktop\x1a\x11proto/Error.proto\x1a#proto/AddPost/DrawThreadPopUp.proto\x1a!proto/AddPost/PostScoreInfo.proto\x1a\x10proto/Anti.proto\x1a\x16proto/ContriInfo.proto\x1a\x19proto/IconStampInfo.proto\x1a\x18proto/PostAntiInfo.proto\x1a\x14proto/ReplyExp.proto\x1a\x19proto/TbInteraction.proto\x1a\x11proto/Toast.proto\x1a\x15proto/VcodeInfo.proto\x1a\x17proto/ZhiBoInfoTW.proto\"\xcf\x05\n\x0f\x44\x61taRes_AddPost\x12\x0f\n\x07opgroup\x18\x01 \x01(\t\x12\x0b\n\x03tid\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\t\x12\x10\n\x08video_id\x18\x04 \x01(\t\x12\x0b\n\x03msg\x18\x05 \x01(\t\x12\x0f\n\x07pre_msg\x18\x06 \x01(\t\x12\x11\n\tcolor_msg\x18\x07 \x01(\t\x12/\n\x0ctwzhibo_info\x18\x08 \x01(\x0b\x32\x19.TiebaDesktop.ZhiBoInfoTW\x12#\n\x03\x65xp\x18\t \x01(\x0b\x32\x16.TiebaDesktop.ReplyExp\x12-\n\x0b\x63ontri_info\x18\n \x01(\x0b\x32\x18.TiebaDesktop.ContriInfo\x12\x34\n\x0ficon_stamp_info\x18\r \x01(\x0b\x32\x1b.TiebaDesktop.IconStampInfo\x12(\n\x04info\x18\x0e \x01(\x0b\x32\x1a.TiebaDesktop.PostAntiInfo\x12%\n\tanti_stat\x18\x0f \x01(\x0b\x32\x12.TiebaDesktop.Anti\x12.\n\ttb_hudong\x18\x10 \x01(\x0b\x32\x1b.TiebaDesktop.TbInteraction\x12%\n\x04\x61nti\x18\x11 \x01(\x0b\x32\x17.TiebaDesktop.VcodeInfo\x12\x0f\n\x07\x65xt_msg\x18\x12 \x01(\t\x12\"\n\x05toast\x18\x13 \x01(\x0b\x32\x13.TiebaDesktop.Toast\x12\x14\n\x0chotmemes_hit\x18\x14 \x03(\t\x12/\n\nscore_info\x18\x15 \x01(\x0b\x32\x1b.TiebaDesktop.PostScoreInfo\x12\x38\n\x11\x64raw_thread_popup\x18\x16 \x01(\x0b\x32\x1d.TiebaDesktop.DrawThreadPopUp\x12\x1d\n\x15\x64raw_thread_has_reply\x18\x17 \x01(\x05\x12\x16\n\x0evaild_task_ids\x18\x18 \x03(\x03\"`\n\rAddPostResIdl\x12\"\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x13.TiebaDesktop.Error\x12+\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1d.TiebaDesktop.DataRes_AddPostb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.AddPost.AddPostResIdl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATARES_ADDPOST._serialized_start=354
  _DATARES_ADDPOST._serialized_end=1073
  _ADDPOSTRESIDL._serialized_start=1075
  _ADDPOSTRESIDL._serialized_end=1171
# @@protoc_insertion_point(module_scope)
