# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/AddPost/DrawThreadPopUp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#proto/AddPost/DrawThreadPopUp.proto\x12\x0cTiebaDesktop\"C\n\x0f\x44rawThreadPopUp\x12\x16\n\x0eis_match_level\x18\x01 \x01(\x05\x12\x18\n\x10need_forum_level\x18\x02 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.AddPost.DrawThreadPopUp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DRAWTHREADPOPUP._serialized_start=53
  _DRAWTHREADPOPUP._serialized_end=120
# @@protoc_insertion_point(module_scope)
