# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/AddPost/PostScoreInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import FeedKV_pb2 as proto_dot_FeedKV__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!proto/AddPost/PostScoreInfo.proto\x12\x0cTiebaDesktop\x1a\x12proto/FeedKV.proto\"t\n\rPostScoreInfo\x12\x11\n\tavg_score\x18\x01 \x01(\t\x12\x16\n\x0etotal_user_num\x18\x02 \x01(\x04\x12,\n\x0escore_user_num\x18\x03 \x03(\x0b\x32\x14.TiebaDesktop.FeedKV\x12\n\n\x02id\x18\x04 \x01(\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.AddPost.PostScoreInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSTSCOREINFO._serialized_start=71
  _POSTSCOREINFO._serialized_end=187
# @@protoc_insertion_point(module_scope)
