# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\Code\TiebaDesktop\resf\qr_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(456, 508)
        Dialog.setStyleSheet("QWidget{font-family: \"微软雅黑\";}\n"
"QDialog{background-color: rgb(255, 255, 255);}\n"
"")
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setContentsMargins(-1, 20, -1, 20)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(92, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setToolTip("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.toolButton = QtWidgets.QToolButton(Dialog)
        self.toolButton.setStyleSheet("QToolButton {\n"
"                background-color: transparent;\n"
"                border: none;\n"
"                border-radius: 6px;\n"
"                padding: 1px;\n"
"                icon-size: 17px;\n"
"                }\n"
"\n"
"                /* 鼠标悬停时：轻微灰色背景 */\n"
"                QToolButton:hover {\n"
"                background-color: rgba(0, 0, 0, 0.08);\n"
"                }\n"
"\n"
"                /* 按下时：更深的背景色，模拟按下效果 */\n"
"                QToolButton:pressed {\n"
"                background-color: rgba(0, 0, 0, 0.15);\n"
"                }\n"
"\n"
"                /* 禁用状态：半透明，显示不可点击 */\n"
"                QToolButton:disabled {\n"
"                background-color: transparent;\n"
"                opacity: 0.4;\n"
"                }\n"
"\n"
"                /* 可选：如果按钮有菜单箭头，也可以美化箭头 */\n"
"                QToolButton::menu-indicator {\n"
"                image: url(:/icons/menu_arrow.png); /* 自定义箭头图标 */\n"
"                subcontrol-position: right center;\n"
"                subcontrol-origin: padding;\n"
"                left: -4px;\n"
"                }")
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.gridLayout_2.setRowStretch(1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(92, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 4)
        self.gridLayout_3.setColumnStretch(1, 10)
        self.gridLayout_3.setColumnStretch(2, 4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "扫码登录"))
        self.label_2.setText(_translate("Dialog", "使用百度贴吧 APP 扫码登录"))
        self.toolButton.setToolTip(_translate("Dialog", "刷新二维码"))
        self.toolButton.setText(_translate("Dialog", "r"))
        self.label.setText(_translate("Dialog", "扫码登录"))
        self.label_3.setText(_translate("Dialog", "QRCodeArea"))
