# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\Code\TiebaDesktop\resf\sign.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(454, 473)
        Dialog.setStyleSheet("QWidget{font-family: \"微软雅黑\";}\n"
"QDialog{background-color: rgb(255, 255, 255);}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setWordWrap(True)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_4, 3, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayout.setStretch(0, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "一键签到"))
        self.groupBox_2.setTitle(_translate("Dialog", "成长等级签到"))
        self.label_2.setText(_translate("Dialog", "将进行 成长等级签到 和 完成分享任务。"))
        self.pushButton_2.setText(_translate("Dialog", "签到"))
        self.groupBox_4.setTitle(_translate("Dialog", "命令行参数调用"))
        self.lineEdit.setText(_translate("Dialog", "[exepath] --sign-all-forums --sign-grows"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "参数"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p>其中，--sign-all-forums 是指签到所有吧， --sign-grows 是指成长等级签到。</p><p>默认情况下，签到操作完成后，会弹出消息框显示签到结果。</p><p>如需静默签到，即完成后不弹窗提示，请添加 --quiet 参数。</p><p>有关命令行用法的详细信息，请参阅 <a href=\"https://github.com/clb-128258/TiebaDesktop/blob/main/env_docs/command-usages.md\"><span style=\" text-decoration: underline; color:#0000ff;\">命令行用法</span></a></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "可在命令行中执行以下命令，实现签到操作。与系统自带的 任务计划程序 配合使用，可实现 定时自动签到/开机自动签到 等功能。"))
        self.groupBox.setTitle(_translate("Dialog", "全部一键签到"))
        self.label.setText(_translate("Dialog", "将进行 成长等级签到 和 全吧签到。"))
        self.pushButton.setText(_translate("Dialog", "一键签到"))
        self.groupBox_3.setTitle(_translate("Dialog", "全吧签到"))
        self.pushButton_3.setText(_translate("Dialog", "全吧签到"))
        self.label_3.setText(_translate("Dialog", "点击右侧的全吧签到按钮进行一键签到。（可签 7 级以下的吧，无视签到高峰期，无视非会员限制）"))
