# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\Code\TiebaDesktop\resf\view_history_single_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(165, 31)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form.setPalette(palette)
        Form.setStyleSheet("QWidget{font-family: \"微软雅黑\";}\n"
"\n"
"\n"
"                QToolButton {\n"
"                background-color: transparent;\n"
"                border: none;\n"
"                border-radius: 6px;\n"
"                padding: 1px;\n"
"                icon-size: 15px;\n"
"                }\n"
"\n"
"                /* 鼠标悬停时：轻微灰色背景 */\n"
"                QToolButton:hover {\n"
"                background-color: rgba(0, 0, 0, 0.08);\n"
"                }\n"
"\n"
"                /* 按下时：更深的背景色，模拟按下效果 */\n"
"                QToolButton:pressed {\n"
"                background-color: rgba(0, 0, 0, 0.15);\n"
"                }\n"
"\n"
"                /* 禁用状态：半透明，显示不可点击 */\n"
"                QToolButton:disabled {\n"
"                background-color: transparent;\n"
"                opacity: 0.4;\n"
"                }\n"
"\n"
"                /* 可选：如果按钮有菜单箭头，也可以美化箭头 */\n"
"                QToolButton::menu-indicator {\n"
"                image: url(:/icons/menu_arrow.png); /* 自定义箭头图标 */\n"
"                subcontrol-position: right center;\n"
"                subcontrol-origin: padding;\n"
"                left: -4px;\n"
"                }\n"
"            ")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 2, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setStyleSheet("QLabel{\n"
"    color: rgb(100,100,100);\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.toolButton_3 = QtWidgets.QToolButton(Form)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_2.addWidget(self.toolButton_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "浏览历史记录子条目"))
        self.label.setText(_translate("Form", "icon"))
        self.label_2.setText(_translate("Form", "history_text"))
        self.label_3.setText(_translate("Form", "time"))
        self.toolButton_3.setToolTip(_translate("Form", "<html><head/><body><p>删除此条记录</p></body></html>"))
        self.toolButton_3.setText(_translate("Form", "X"))
